package skills

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// GeneratedSkills returns the codegen'd skill registry. B2b P1 has no runtime
// consumer; the accessor exists so tests can assert the generated registry
// stays semantically in sync with the on-disk loader.
func GeneratedSkills() []*Skill { return generatedSkills }

// GenerateRegistry scans root/*/SKILL.md and returns the gofmt-formatted source
// of registry_gen.go: a deterministic, name-sorted slice of *Skill literals.
// Both cmd/skillgen and the drift test call this, so there is exactly one
// generator and the byte-identity / digest gates cannot diverge from it.
func GenerateRegistry(root string) ([]byte, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("skillgen: read root %q: %w", root, err)
	}
	var loaded []*Skill
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		path := filepath.Join(root, e.Name(), SkillFileName)
		if _, statErr := os.Stat(path); statErr != nil {
			continue
		}
		s, parseErr := ParseSkillFile(path)
		if parseErr != nil {
			return nil, fmt.Errorf("skillgen: parse %q: %w", path, parseErr)
		}
		s.bodyFS = os.DirFS(root)
		if s.IntentLabel != "" || s.HandlerKey != "" || len(s.ReactToolSubset) > 0 {
			return nil, fmt.Errorf("skillgen: skill %q carries deterministic routing metadata; use internal/routing/<name>/route.yaml", s.Name)
		}
		if gateErr := ValidateSkillRegistration(s); gateErr != nil {
			return nil, fmt.Errorf("skillgen: %w", gateErr)
		}
		loaded = append(loaded, s)
	}
	// Sort by name so codegen output is deterministic; Go map/dir iteration
	// order would otherwise make the digest pin + byte-identity gate flaky
	// (B2b section 3 F4).
	sort.Slice(loaded, func(i, j int) bool { return loaded[i].Name < loaded[j].Name })

	var b strings.Builder
	b.WriteString("// Code generated by cmd/skillgen; DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `go generate ./internal/skills`.\n\n")
	b.WriteString("package skills\n\n")
	b.WriteString("// generatedSkills is the codegen mirror of internal/skills/*/SKILL.md, sorted\n")
	b.WriteString("// by Name for byte-stable output. B2b P1 has no runtime consumer; the drift\n")
	b.WriteString("// test + digest pin keep it in sync with disk.\n")
	b.WriteString("var generatedSkills = []*Skill{\n")
	for _, s := range loaded {
		writeSkillLiteral(&b, s)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("skillgen: gofmt generated source: %w", err)
	}
	return formatted, nil
}

// writeSkillLiteral emits one *Skill composite literal, omitting zero-valued
// fields. Omission is deterministic (a given parsed skill always yields the same
// non-zero field set) and keeps the generated file readable.
func writeSkillLiteral(b *strings.Builder, s *Skill) {
	b.WriteString("{\n")
	field := func(name, lit string) { fmt.Fprintf(b, "%s: %s,\n", name, lit) }
	field("Name", strconv.Quote(s.Name))
	field("Description", strconv.Quote(s.Description))
	if len(s.Triggers) > 0 {
		field("Triggers", quoteSlice(s.Triggers))
	}
	if len(s.ApplicableTiers) > 0 {
		field("ApplicableTiers", quoteSlice(s.ApplicableTiers))
	}
	if len(s.RequiredTools) > 0 {
		field("RequiredTools", quoteSlice(s.RequiredTools))
	}
	if len(s.RelatedSkills) > 0 {
		field("RelatedSkills", quoteSlice(s.RelatedSkills))
	}
	if s.BodyCapLines != 0 {
		field("BodyCapLines", strconv.Itoa(s.BodyCapLines))
	}
	field("VerificationStatus", strconv.Quote(s.VerificationStatus))
	if s.FieldRefsVerified {
		field("FieldRefsVerified", "true")
	}
	if s.IntentLabel != "" {
		field("IntentLabel", strconv.Quote(s.IntentLabel))
	}
	if s.SkillGroup != "" {
		field("SkillGroup", strconv.Quote(s.SkillGroup))
	}
	if s.RequiredCitation {
		field("RequiredCitation", "true")
	}
	if s.HandlerKey != "" {
		field("HandlerKey", strconv.Quote(s.HandlerKey))
	}
	if len(s.ReactToolSubset) > 0 {
		field("ReactToolSubset", quoteSlice(s.ReactToolSubset))
	}
	if len(s.PlannerDirectives) > 0 {
		field("PlannerDirectives", quoteSlice(s.PlannerDirectives))
	}
	if len(s.PlannerExamples) > 0 {
		field("PlannerExamples", plannerExamplesLit(s.PlannerExamples))
	}
	if s.Provenance != "" {
		field("Provenance", strconv.Quote(s.Provenance))
	}
	if s.ProvenanceTraceRef != "" {
		field("ProvenanceTraceRef", strconv.Quote(s.ProvenanceTraceRef))
	}
	if s.SkillVersion != 0 {
		field("SkillVersion", strconv.Itoa(s.SkillVersion))
	}
	if s.LastValidatedAgainst != "" {
		field("LastValidatedAgainst", strconv.Quote(s.LastValidatedAgainst))
	}
	if s.HumanReviewed {
		field("HumanReviewed", "true")
	}
	if s.Sanitized {
		field("Sanitized", "true")
	}
	if s.EvalPassed {
		field("EvalPassed", "true")
	}
	if !emptyResources(s.Resources) {
		field("Resources", skillResourcesLit(s.Resources))
	}
	field("Path", strconv.Quote(s.Path))
	b.WriteString("},\n")
}

func quoteSlice(items []string) string {
	parts := make([]string, len(items))
	for i, it := range items {
		parts[i] = strconv.Quote(it)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func plannerExamplesLit(exs []SkillPlannerExample) string {
	parts := make([]string, len(exs))
	for i, ex := range exs {
		parts[i] = fmt.Sprintf("{Question: %s, Confidence: %s}",
			strconv.Quote(ex.Question),
			strconv.FormatFloat(ex.Confidence, 'g', -1, 64))
	}
	return "[]SkillPlannerExample{" + strings.Join(parts, ", ") + "}"
}

func emptyResources(r SkillResources) bool {
	return len(r.Scripts) == 0 && len(r.References) == 0 && len(r.Tests) == 0
}

func skillResourcesLit(r SkillResources) string {
	var fields []string
	if len(r.Scripts) > 0 {
		fields = append(fields, "Scripts: "+quoteSlice(r.Scripts))
	}
	if len(r.References) > 0 {
		fields = append(fields, "References: "+quoteSlice(r.References))
	}
	if len(r.Tests) > 0 {
		fields = append(fields, "Tests: "+quoteSlice(r.Tests))
	}
	return "SkillResources{" + strings.Join(fields, ", ") + "}"
}
