package skills

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// knownHandlerKeys is the hand-maintained allow-list of handler_key values
// codegen accepts (mirrors the registry/frontmatter parity panic in
// internal/intent/capability_registry.go:144-164). These are STRINGS, not func
// pointers, so internal/skills stays free of an internal/intent import cycle;
// the func binding lives in internal/intent (CapabilityHandlerForKey). The two
// hand-maintained sets are kept in lockstep by an internal/intent test
// (TestCapabilityHandlerByKey_MatchesKnownHandlerKeys) that asserts that
// binding's key set equals KnownHandlerKeys() below; the cross-package parity
// guard. Without it the two maps could drift silently across the package boundary.
//
// B2b P2 populated this with the migrated capability handlers. The seeded
// diagnose_* skills declare no handler_key (agent-tier playbooks, no
// deterministic handler), so they are unaffected.
var knownHandlerKeys = map[string]bool{
	"handleGPUSpecsQuery":        true,
	"handleStockAvailability":    true,
	"handleNetAcceleratorStatus": true,
	"handlePlatformImageList":    true,
	"handleCustomImageList":      true,
	"handleCommunityImageList":   true,
	"handlePricingQuery":         true,
}

// KnownHandlerKeys returns the sorted handler_key allow-list codegen validates
// skills against. internal/intent uses it to assert its handler-binding map
// (capabilityHandlerByKey) covers exactly this set, so the two cross-package
// hand-maintained sets cannot drift unnoticed.
func KnownHandlerKeys() []string {
	keys := make([]string, 0, len(knownHandlerKeys))
	for k := range knownHandlerKeys {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// GeneratedSkills returns the codegen'd skill registry. B2b P1 has no runtime
// consumer; the accessor exists so tests can assert the generated registry
// stays semantically in sync with the on-disk loader.
func GeneratedSkills() []*Skill { return generatedSkills }

// GenerateRegistry scans root/*/SKILL.md and returns the gofmt-formatted source
// of registry_gen.go: a deterministic, name-sorted slice of *Skill literals.
// Both cmd/skillgen and the drift test call this, so there is exactly one
// generator and the byte-identity / digest gates cannot diverge from it.
func GenerateRegistry(root string) ([]byte, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("skillgen: read root %q: %w", root, err)
	}
	var loaded []*Skill
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		path := filepath.Join(root, e.Name(), SkillFileName)
		if _, statErr := os.Stat(path); statErr != nil {
			continue
		}
		s, parseErr := ParseSkillFile(path)
		if parseErr != nil {
			return nil, fmt.Errorf("skillgen: parse %q: %w", path, parseErr)
		}
		s.bodyFS = os.DirFS(root)
		// Generate-time existence check (B2b section 4): a declared handler_key must
		// resolve. No-op in P1 (no diagnose_* skill declares one).
		if s.HandlerKey != "" && !knownHandlerKeys[s.HandlerKey] {
			return nil, fmt.Errorf("skillgen: skill %q handler_key %q not in knownHandlerKeys (add the binding before generating)", s.Name, s.HandlerKey)
		}
		if gateErr := ValidateSkillRegistration(s); gateErr != nil {
			return nil, fmt.Errorf("skillgen: %w", gateErr)
		}
		loaded = append(loaded, s)
	}
	// Sort by name so codegen output is deterministic; Go map/dir iteration
	// order would otherwise make the digest pin + byte-identity gate flaky
	// (B2b section 3 F4).
	sort.Slice(loaded, func(i, j int) bool { return loaded[i].Name < loaded[j].Name })

	var b strings.Builder
	b.WriteString("// Code generated by cmd/skillgen; DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `go generate ./internal/skills`.\n\n")
	b.WriteString("package skills\n\n")
	b.WriteString("// generatedSkills is the codegen mirror of internal/skills/*/SKILL.md, sorted\n")
	b.WriteString("// by Name for byte-stable output. B2b P1 has no runtime consumer; the drift\n")
	b.WriteString("// test + digest pin keep it in sync with disk.\n")
	b.WriteString("var generatedSkills = []*Skill{\n")
	for _, s := range loaded {
		writeSkillLiteral(&b, s)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("skillgen: gofmt generated source: %w", err)
	}
	return formatted, nil
}

// writeSkillLiteral emits one *Skill composite literal, omitting zero-valued
// fields. Omission is deterministic (a given parsed skill always yields the same
// non-zero field set) and keeps the generated file readable.
func writeSkillLiteral(b *strings.Builder, s *Skill) {
	b.WriteString("{\n")
	field := func(name, lit string) { fmt.Fprintf(b, "%s: %s,\n", name, lit) }
	field("Name", strconv.Quote(s.Name))
	field("Description", strconv.Quote(s.Description))
	if len(s.Triggers) > 0 {
		field("Triggers", quoteSlice(s.Triggers))
	}
	if len(s.ApplicableTiers) > 0 {
		field("ApplicableTiers", quoteSlice(s.ApplicableTiers))
	}
	if len(s.RequiredTools) > 0 {
		field("RequiredTools", quoteSlice(s.RequiredTools))
	}
	if len(s.RelatedSkills) > 0 {
		field("RelatedSkills", quoteSlice(s.RelatedSkills))
	}
	if s.BodyCapLines != 0 {
		field("BodyCapLines", strconv.Itoa(s.BodyCapLines))
	}
	field("VerificationStatus", strconv.Quote(s.VerificationStatus))
	if s.FieldRefsVerified {
		field("FieldRefsVerified", "true")
	}
	if s.IntentLabel != "" {
		field("IntentLabel", strconv.Quote(s.IntentLabel))
	}
	if s.SkillGroup != "" {
		field("SkillGroup", strconv.Quote(s.SkillGroup))
	}
	if s.RequiredCitation {
		field("RequiredCitation", "true")
	}
	if s.HandlerKey != "" {
		field("HandlerKey", strconv.Quote(s.HandlerKey))
	}
	if len(s.ReactToolSubset) > 0 {
		field("ReactToolSubset", quoteSlice(s.ReactToolSubset))
	}
	if len(s.PlannerDirectives) > 0 {
		field("PlannerDirectives", quoteSlice(s.PlannerDirectives))
	}
	if len(s.PlannerExamples) > 0 {
		field("PlannerExamples", plannerExamplesLit(s.PlannerExamples))
	}
	if s.Provenance != "" {
		field("Provenance", strconv.Quote(s.Provenance))
	}
	if s.ProvenanceTraceRef != "" {
		field("ProvenanceTraceRef", strconv.Quote(s.ProvenanceTraceRef))
	}
	if s.SkillVersion != 0 {
		field("SkillVersion", strconv.Itoa(s.SkillVersion))
	}
	if s.LastValidatedAgainst != "" {
		field("LastValidatedAgainst", strconv.Quote(s.LastValidatedAgainst))
	}
	if s.HumanReviewed {
		field("HumanReviewed", "true")
	}
	if s.Sanitized {
		field("Sanitized", "true")
	}
	if s.EvalPassed {
		field("EvalPassed", "true")
	}
	if !emptyResources(s.Resources) {
		field("Resources", skillResourcesLit(s.Resources))
	}
	field("Path", strconv.Quote(s.Path))
	b.WriteString("},\n")
}

func quoteSlice(items []string) string {
	parts := make([]string, len(items))
	for i, it := range items {
		parts[i] = strconv.Quote(it)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func plannerExamplesLit(exs []SkillPlannerExample) string {
	parts := make([]string, len(exs))
	for i, ex := range exs {
		parts[i] = fmt.Sprintf("{Question: %s, Confidence: %s}",
			strconv.Quote(ex.Question),
			strconv.FormatFloat(ex.Confidence, 'g', -1, 64))
	}
	return "[]SkillPlannerExample{" + strings.Join(parts, ", ") + "}"
}

func emptyResources(r SkillResources) bool {
	return len(r.Scripts) == 0 && len(r.References) == 0 && len(r.Tests) == 0
}

func skillResourcesLit(r SkillResources) string {
	var fields []string
	if len(r.Scripts) > 0 {
		fields = append(fields, "Scripts: "+quoteSlice(r.Scripts))
	}
	if len(r.References) > 0 {
		fields = append(fields, "References: "+quoteSlice(r.References))
	}
	if len(r.Tests) > 0 {
		fields = append(fields, "Tests: "+quoteSlice(r.Tests))
	}
	return "SkillResources{" + strings.Join(fields, ", ") + "}"
}
