// Code generated by cmd/skillgen; DO NOT EDIT.
// Regenerate with `go generate ./internal/skills`.

package skills

// generatedSkills is the codegen mirror of internal/skills/*/skill.md, sorted
// by Name for byte-stable output. B2b P1 has no runtime consumer; the drift
// test + digest pin keep it in sync with disk.
var generatedSkills = []*Skill{
	{
		Name:               "diagnose_gpu_not_detected",
		Description:        "Use this skill when user reports nvidia-smi error / GPU not detected / CUDA unavailable on a CompShare instance and needs read-only platform-side triage",
		Triggers:           []string{"nvidia-smi 报错", "GPU 不识别", "CUDA 不可用", "GPU 检测不到", "nvidia-smi 找不到设备"},
		ApplicableTiers:    []string{"agent"},
		RequiredTools:      []string{"DescribeCompShareInstance", "GetCompShareInstanceMonitor"},
		RelatedSkills:      []string{"safety_warning"},
		BodyCapLines:       100,
		VerificationStatus: "unverified",
		Provenance:         "human_authored",
		Path:               "diagnose_gpu_not_detected/skill.md",
	},
	{
		Name:               "diagnose_image_issue",
		Description:        "Use this skill when user suspects a CompShare instance image issue (image fails to install, community image misbehaving, image incompatible with application) and needs read-only platform-side triage",
		Triggers:           []string{"镜像问题", "镜像无法启动", "社区镜像有问题", "怀疑镜像 bug", "镜像装不上"},
		ApplicableTiers:    []string{"agent"},
		RequiredTools:      []string{"DescribeCompShareInstance"},
		RelatedSkills:      []string{"safety_warning"},
		BodyCapLines:       100,
		VerificationStatus: "unverified",
		Provenance:         "human_authored",
		Path:               "diagnose_image_issue/skill.md",
	},
	{
		Name:               "diagnose_init_failure",
		Description:        "Use this skill when user reports CompShare instance stuck in Install / Install Fail state, or instance not starting after creation, and needs read-only platform-side triage",
		Triggers:           []string{"实例没启动", "实例初始化失败", "Install Fail", "实例创建后没起来", "实例卡在 Install"},
		ApplicableTiers:    []string{"agent"},
		RequiredTools:      []string{"DescribeCompShareInstance"},
		RelatedSkills:      []string{"safety_warning"},
		BodyCapLines:       100,
		VerificationStatus: "unverified",
		Provenance:         "human_authored",
		Path:               "diagnose_init_failure/skill.md",
	},
	{
		Name:               "diagnose_port_firewall",
		Description:        "Use this skill when user reports a CompShare instance service port unreachable (JupyterLab / FileBrowser / custom apps) — for SSH failure use diagnose_ssh instead",
		Triggers:           []string{"端口不通", "服务访问不到", "JupyterLab 进不去", "FileBrowser 无法访问", "应用端口被防火墙拦"},
		ApplicableTiers:    []string{"agent"},
		RequiredTools:      []string{"DescribeCompShareInstance", "DescribeCompShareSoftwarePort"},
		RelatedSkills:      []string{"safety_warning"},
		BodyCapLines:       100,
		VerificationStatus: "unverified",
		Provenance:         "human_authored",
		Path:               "diagnose_port_firewall/skill.md",
	},
	{
		Name:               "diagnose_ssh",
		Description:        "Use this skill when user reports SSH connection failure / timeout / Permission denied on a CompShare instance and needs read-only platform-side triage",
		Triggers:           []string{"SSH 连不上", "SSH 连接超时", "Permission denied", "SSH 连接失败", "无法登录实例"},
		ApplicableTiers:    []string{"agent"},
		RequiredTools:      []string{"DescribeCompShareInstance", "GetCompShareInstanceMonitor"},
		RelatedSkills:      []string{"safety_warning"},
		BodyCapLines:       100,
		VerificationStatus: "unverified",
		Provenance:         "human_authored",
		Path:               "diagnose_ssh/skill.md",
	},
}
