package routing

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

var knownHandlerKeys = map[string]bool{
	"handleGPUSpecsQuery":        true,
	"handleStockAvailability":    true,
	"handleNetAcceleratorStatus": true,
	"handleImageTagCatalog":      true,
	"handlePlatformImageList":    true,
	"handleCustomImageList":      true,
	"handleCommunityImageList":   true,
	"handlePricingQuery":         true,
}

func KnownHandlerKeys() []string {
	keys := make([]string, 0, len(knownHandlerKeys))
	for key := range knownHandlerKeys {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func GeneratedRoutes() []*Route { return generatedRoutes }

func GenerateRegistry(root string) ([]byte, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("routegen: read root %q: %w", root, err)
	}
	var loaded []*Route
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		path := filepath.Join(root, e.Name(), RouteFileName)
		if _, statErr := os.Stat(path); statErr != nil {
			continue
		}
		route, parseErr := ParseRouteFile(path)
		if parseErr != nil {
			return nil, fmt.Errorf("routegen: parse %q: %w", path, parseErr)
		}
		if !knownHandlerKeys[route.HandlerKey] {
			return nil, fmt.Errorf("routegen: route %q handler_key %q not in knownHandlerKeys", route.Name, route.HandlerKey)
		}
		loaded = append(loaded, route)
	}
	sort.Slice(loaded, func(i, j int) bool { return loaded[i].Name < loaded[j].Name })

	var b strings.Builder
	b.WriteString("// Code generated by cmd/routegen; DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `go generate ./internal/routing`.\n\n")
	b.WriteString("package routing\n\n")
	b.WriteString("// generatedRoutes is the codegen mirror of internal/routing/*/route.yaml, sorted by Name.\n")
	b.WriteString("var generatedRoutes = []*Route{\n")
	for _, route := range loaded {
		writeRouteLiteral(&b, route)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("routegen: gofmt generated source: %w", err)
	}
	return formatted, nil
}

func writeRouteLiteral(b *strings.Builder, route *Route) {
	b.WriteString("{\n")
	field := func(name, lit string) { fmt.Fprintf(b, "%s: %s,\n", name, lit) }
	field("Name", strconv.Quote(route.Name))
	field("Description", strconv.Quote(route.Description))
	field("IntentLabel", strconv.Quote(route.IntentLabel))
	field("RouteGroup", strconv.Quote(route.RouteGroup))
	field("RequiredTools", quoteSlice(route.RequiredTools))
	field("ToolSubset", quoteSlice(route.ToolSubset))
	if route.RequiredCitation {
		field("RequiredCitation", "true")
	}
	field("HandlerKey", strconv.Quote(route.HandlerKey))
	if len(route.PlannerDirectives) > 0 {
		field("PlannerDirectives", quoteSlice(route.PlannerDirectives))
	}
	if len(route.PlannerExamples) > 0 {
		field("PlannerExamples", plannerExamplesLit(route.PlannerExamples))
	}
	field("VerificationStatus", strconv.Quote(route.VerificationStatus))
	if route.FieldRefsVerified {
		field("FieldRefsVerified", "true")
	}
	if route.Provenance != "" {
		field("Provenance", strconv.Quote(route.Provenance))
	}
	field("Path", strconv.Quote(route.Path))
	b.WriteString("},\n")
}

func quoteSlice(items []string) string {
	parts := make([]string, len(items))
	for i, item := range items {
		parts[i] = strconv.Quote(item)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func plannerExamplesLit(examples []PlannerExample) string {
	parts := make([]string, len(examples))
	for i, ex := range examples {
		parts[i] = fmt.Sprintf("{Question: %s, Confidence: %s}",
			strconv.Quote(ex.Question),
			strconv.FormatFloat(ex.Confidence, 'g', -1, 64))
	}
	return "[]PlannerExample{" + strings.Join(parts, ", ") + "}"
}
